import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/starlitehomepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Starlitehomepage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/mediapage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Mediapage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactform" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Contactform
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/header" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Header
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutuspage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Aboutuspage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/blogpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Blogpage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/singleblogpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Singleblogpage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/nutrition" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Nutrition
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/fitness" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Fitness
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/healing" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Healing
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wellness" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Wellness
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/testimonial" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Testimonial
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
